### ISSUE TITLE
Need to be able to disable TemplateHelper for scripts like postinst

### ISSUE THREAD

**Issue by nik9000** [nebula-plugins/gradle-ospackage-plugin#138]
It looks like the deb generator tries to add some helpful templates for stuff like postinst. Since our project already has fully fleshed out scripts these just get in the way. There should be a simple option to turn these off.

**Comment by nik9000** [comment]
Or - maybe a better option - is to make it simpler and better documented how to override the default templates.

**Comment by bmoyles** [comment]
cc @coryb @rspieldenner @DanielThomas 

This is actually an issue I wanted to raise myself -- IMO when postInstall or preInstall are provided with a file, that should be used as-is or there should be a distinct directive for directly including a file rather than wrapping it with a template.

I'm about to open a similar issue for nebula-ospackage-plugin, specifically nebula.ospackage-daemon as I think the same could be said for the command and logCommand vars in daemon{} blocks

**Comment by sghill** [comment]
@nik9000 I think the new `*File` directives [documented here](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin#scripts) cover this use case. Would you mind trying out and reporting back?
