### ISSUE TITLE
RPM task never up-to-date

### ISSUE THREAD

**Issue by jfbibeau** [nebula-plugins/gradle-ospackage-plugin#202]
Getting the following debug output, can't get my rpm task to be UP-TO-DATE after running it twice in a row:

```
16:44:08.649 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':activemq:rpm' is up-to-date
16:44:08.722 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':activemq:rpm' (up-to-date check took 0.073 secs) due to:
  Value of input property 'allDependencies' has changed for task ':activemq:rpm'
```

Could be a regression of this?
https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/161

**Comment by sghill** [comment]
I tried this out with a fairly simple `ospackage` block, and subsequent runs were marked `UP-TO-DATE`. I'm using v4.3.0 with gradle 3.2.1. It's possible it has been fixed in one of the recent releases. If you're still getting the issue can you share a test or example setup that demonstrates the problem?

```gradle
plugins {
    id 'java'
    id 'nebula.ospackage' version '4.3.0'
}

ospackage {
    release '1'
    version '1.0.0'
    from (jar.outputs.files) {
        into '/lib'
    }
}
```

**Comment by jfbibeau** [comment]
Confirmed the issue is fixed!
