### ISSUE TITLE
link() ignore user and permissionGroup

### ISSUE THREAD

**Issue by jr4u** [nebula-plugins/gradle-ospackage-plugin#320]
User and permissionGroup of links allways generated with root:root and ignore the supplied defaults. Also there is no posibility to add specific user/permissionGroup for a link.

**Comment by schwingmar** [comment]
Since this issue is blocking me from using the plugin, I created a fix for it.
With this PR #436 the defaults are taken from the task and the link can be created with
- only source and target,
- source, target and file permissions,
- source, target and user+group
- or all options.

The fix is, fortunately, not complicated since the underlying redline rpm builder already had the options available.

**Comment by borisbrodski** [comment]
Please, merge this PR and create an official release 👍
